In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA

In [6]:
pima=pd.read_csv("pima-indians-diabetes.csv",header=None,names=col_names)
col_names=["Number of times pregnant","Plasma glucose concentration a 2 hours in an oral glucose tolerance test","Diastolic blood pressure (mm Hg)","Triceps skin fold thickness (mm)","2-Hour serum insulin (mu U/ml)","Body mass index (weight in kg/(height in m)^2)","Diabetes pedigree function","Age (years)","Class variable (0 or 
1)"]

NameError: name 'col_names' is not defined

In [12]:
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age','label']
pima=pd.read_csv("pima-indians-diabetes.csv",header=None,names=col_names)           
           

In [14]:
pima

pregnant  glucose    bp  skin  \
0                        # 1. Number of times pregnant      NaN   NaN   NaN   
1    # 2. Plasma glucose concentration a 2 hours in...      NaN   NaN   NaN   
2                # 3. Diastolic blood pressure (mm Hg)      NaN   NaN   NaN   
3                # 4. Triceps skin fold thickness (mm)      NaN   NaN   NaN   
4                  # 5. 2-Hour serum insulin (mu U/ml)      NaN   NaN   NaN   
5    # 6. Body mass index (weight in kg/(height in ...      NaN   NaN   NaN   
6                      # 7. Diabetes pedigree function      NaN   NaN   NaN   
7                                     # 8. Age (years)      NaN   NaN   NaN   
8                         # 9. Class variable (0 or 1)      NaN   NaN   NaN   
9                                                    6    148.0  72.0  35.0   
10                                                   1     85.0  66.0  29.0   
11                                                   8    183.0  64.0   0.0   
12                                                   1     89.0  66.0  23.0   
13                                                   0    137.0  40.0  35.0   
14                                                   5    116.0  74.0   0.0   
15                                                   3     78.0  50.0  32.0   
16                                                  10    115.0   0.0   0.0   
17                                                   2    197.0  70.0  45.0   
18                                                   8    125.0  96.0   0.0   
19                                                   4    110.0  92.0   0.0   
20                                                  10    168.0  74.0   0.0   
21                                                  10    139.0  80.0   0.0   
22                                                   1    189.0  60.0  23.0   
23                                                   5    166.0  72.0  19.0   
24                                                   7    100.0   0.0   0.0   
25                                                   0    118.0  84.0  47.0   
26                                                   7    107.0  74.0   0.0   
27                                                   1    103.0  30.0  38.0   
28                                                   1    115.0  70.0  30.0   
29                                                   3    126.0  88.0  41.0   
..                                                 ...      ...   ...   ...   
747                                                  2     99.0  60.0  17.0   
748                                                  1    102.0  74.0   0.0   
749                                                 11    120.0  80.0  37.0   
750                                                  3    102.0  44.0  20.0   
751                                                  1    109.0  58.0  18.0   
752                                                  9    140.0  94.0   0.0   
753                                                 13    153.0  88.0  37.0   
754                                                 12    100.0  84.0  33.0   
755                                                  1    147.0  94.0  41.0   
756                                                  1     81.0  74.0  41.0   
757                                                  3    187.0  70.0  22.0   
758                                                  6    162.0  62.0   0.0   
759                                                  4    136.0  70.0   0.0   
760                                                  1    121.0  78.0  39.0   
761                                                  3    108.0  62.0  24.0   
762                                                  0    181.0  88.0  44.0   
763                                                  8    154.0  78.0  32.0   
764                                                  1    128.0  88.0  39.0   
765                                                  7    137.0  90.0  41.0   
766              

In [17]:
df=pd.DataFrame(data=pima)

In [18]:
df=df.iloc[9:776,:]

In [22]:
df=df.reset_index(drop=True)

In [23]:
df

pregnant  glucose    bp  skin  insulin   bmi  pedigree   age  label
0          6    148.0  72.0  35.0      0.0  33.6     0.627  50.0    1.0
1          1     85.0  66.0  29.0      0.0  26.6     0.351  31.0    0.0
2          8    183.0  64.0   0.0      0.0  23.3     0.672  32.0    1.0
3          1     89.0  66.0  23.0     94.0  28.1     0.167  21.0    0.0
4          0    137.0  40.0  35.0    168.0  43.1     2.288  33.0    1.0
5          5    116.0  74.0   0.0      0.0  25.6     0.201  30.0    0.0
6          3     78.0  50.0  32.0     88.0  31.0     0.248  26.0    1.0
7         10    115.0   0.0   0.0      0.0  35.3     0.134  29.0    0.0
8          2    197.0  70.0  45.0    543.0  30.5     0.158  53.0    1.0
9          8    125.0  96.0   0.0      0.0   0.0     0.232  54.0    1.0
10         4    110.0  92.0   0.0      0.0  37.6     0.191  30.0    0.0
11        10    168.0  74.0   0.0      0.0  38.0     0.537  34.0    1.0
12        10    139.0  80.0   0.0      0.0  27.1     1.441  57.0    0.0
13         1    189.0  60.0  23.0    846.0  30.1     0.398  59.0    1.0
14         5    166.0  72.0  19.0    175.0  25.8     0.587  51.0    1.0
15         7    100.0   0.0   0.0      0.0  30.0     0.484  32.0    1.0
16         0    118.0  84.0  47.0    230.0  45.8     0.551  31.0    1.0
17         7    107.0  74.0   0.0      0.0  29.6     0.254  31.0    1.0
18         1    103.0  30.0  38.0     83.0  43.3     0.183  33.0    0.0
19         1    115.0  70.0  30.0     96.0  34.6     0.529  32.0    1.0
20         3    126.0  88.0  41.0    235.0  39.3     0.704  27.0    0.0
21         8     99.0  84.0   0.0      0.0  35.4     0.388  50.0    0.0
22         7    196.0  90.0   0.0      0.0  39.8     0.451  41.0    1.0
23         9    119.0  80.0  35.0      0.0  29.0     0.263  29.0    1.0
24        11    143.0  94.0  33.0    146.0  36.6     0.254  51.0    1.0
25        10    125.0  70.0  26.0    115.0  31.1     0.205  41.0    1.0
26         7    147.0  76.0   0.0      0.0  39.4     0.257  43.0    1.0
27         1     97.0  66.0  15.0    140.0  23.2     0.487  22.0    0.0
28        13    145.0  82.0  19.0    110.0  22.2     0.245  57.0    0.0
29         5    117.0  92.0   0.0      0.0  34.1     0.337  38.0    0.0
..       ...      ...   ...   ...      ...   ...       ...   ...    ...
737        8     65.0  72.0  23.0      0.0  32.0     0.600  42.0    0.0
738        2     99.0  60.0  17.0    160.0  36.6     0.453  21.0    0.0
739        1    102.0  74.0   0.0      0.0  39.5     0.293  42.0    1.0
740       11    120.0  80.0  37.0    150.0  42.3     0.785  48.0    1.0
741        3    102.0  44.0  20.0     94.0  30.8     0.400  26.0    0.0
742        1    109.0  58.0  18.0    116.0  28.5     0.219  22.0    0.0
743        9    140.0  94.0   0.0      0.0  32.7     0.734  45.0    1.0
744       13    153.0  88.0  37.0    140.0  40.6     1.174  39.0    0.0
745       12    100.0  84.0  33.0    105.0  30.0     0.488  46.0    0.0
746        1    147.0  94.0  41.0      0.0  49.3     0.358  27.0    1.0
747        1     81.0  74.0  41.0     57.0  46.3     1.096  32.0    0.0
748        3    187.0  70.0  22.0    200.0  36.4     0.408  36.0    1.0
749        6    162.0  62.0   0.0      0.0  24.3     0.178  50.0    1.0
750        4    136.0  70.0   0.0      0.0  31.2     1.182  22.0    1.0
751        1    121.0  78.0  39.0     74.0  39.0     0.261  28.0    0.0
752        3    108.0  62.0  24.0      0.0  26.0     0.223  25.0    0.0
753        0    181.0  88.0  44.0    510.0  43.3     0.222  26.0    1.0
754        8    154.0  78.0  32.0      0.0  32.4     0.443  45.0    1.0
755        1    128.0  88.0  39.0    110.0  36.5     1.057  37.0    1.0
756        7    137.0  90.0  41.0      0.0  32.0     0.391  39.0    0.0
757        0    123.0  72.0   0.0      0.0  36.3     0.258  52.0    1.0
758        1    106.0  76.0   0.0      0.0  37.5     0.197  26.0    0.0
759        6    190.0  92.0   0.0      0.0  35.5     0.278  66.0    1.0
760        2     88.0  58.0  26.0     16.0  

In [24]:
df.isnull().sum()

pregnant    0
glucose     0
bp          0
skin        0
insulin     0
bmi         0
pedigree    0
age         0
label       0
dtype: int64

In [25]:
df.head()

pregnant  glucose    bp  skin  insulin   bmi  pedigree   age  label
0        6    148.0  72.0  35.0      0.0  33.6     0.627  50.0    1.0
1        1     85.0  66.0  29.0      0.0  26.6     0.351  31.0    0.0
2        8    183.0  64.0   0.0      0.0  23.3     0.672  32.0    1.0
3        1     89.0  66.0  23.0     94.0  28.1     0.167  21.0    0.0
4        0    137.0  40.0  35.0    168.0  43.1     2.288  33.0    1.0

In [26]:
df.shape

(767, 9)

In [27]:
df.dtypes

pregnant     object
glucose     float64
bp          float64
skin        float64
insulin     float64
bmi         float64
pedigree    float64
age         float64
label       float64
dtype: object

In [28]:
df.describe()

glucose          bp        skin     insulin         bmi    pedigree  \
count  767.000000  767.000000  767.000000  767.000000  767.000000  767.000000   
mean   120.930900   69.104302   20.522816   79.903520   31.994654    0.472081   
std     31.977581   19.368410   15.958143  115.283105    7.889095    0.331496   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.078000   
25%     99.000000   62.000000    0.000000    0.000000   27.300000    0.243500   
50%    117.000000   72.000000   23.000000   32.000000   32.000000    0.374000   
75%    140.500000   80.000000   32.000000  127.500000   36.600000    0.626500   
max    199.000000  122.000000   99.000000  846.000000   67.100000    2.420000   

              age       label  
count  767.000000  767.000000  
mean    33.254237    0.349413  
std     11.762079    0.477096  
min     21.000000    0.000000  
25%     24.000000    0.000000  
50%     29.000000    0.000000  
75%     41.000000    1.000000  
max     81.000000    1.000000

In [52]:
feature_columns = [ 'pregnant','glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age']
x=df[feature_columns]
x

pregnant  glucose    bp  skin  insulin   bmi  pedigree   age
0          6    148.0  72.0  35.0      0.0  33.6     0.627  50.0
1          1     85.0  66.0  29.0      0.0  26.6     0.351  31.0
2          8    183.0  64.0   0.0      0.0  23.3     0.672  32.0
3          1     89.0  66.0  23.0     94.0  28.1     0.167  21.0
4          0    137.0  40.0  35.0    168.0  43.1     2.288  33.0
5          5    116.0  74.0   0.0      0.0  25.6     0.201  30.0
6          3     78.0  50.0  32.0     88.0  31.0     0.248  26.0
7         10    115.0   0.0   0.0      0.0  35.3     0.134  29.0
8          2    197.0  70.0  45.0    543.0  30.5     0.158  53.0
9          8    125.0  96.0   0.0      0.0   0.0     0.232  54.0
10         4    110.0  92.0   0.0      0.0  37.6     0.191  30.0
11        10    168.0  74.0   0.0      0.0  38.0     0.537  34.0
12        10    139.0  80.0   0.0      0.0  27.1     1.441  57.0
13         1    189.0  60.0  23.0    846.0  30.1     0.398  59.0
14         5    166.0  72.0  19.0    175.0  25.8     0.587  51.0
15         7    100.0   0.0   0.0      0.0  30.0     0.484  32.0
16         0    118.0  84.0  47.0    230.0  45.8     0.551  31.0
17         7    107.0  74.0   0.0      0.0  29.6     0.254  31.0
18         1    103.0  30.0  38.0     83.0  43.3     0.183  33.0
19         1    115.0  70.0  30.0     96.0  34.6     0.529  32.0
20         3    126.0  88.0  41.0    235.0  39.3     0.704  27.0
21         8     99.0  84.0   0.0      0.0  35.4     0.388  50.0
22         7    196.0  90.0   0.0      0.0  39.8     0.451  41.0
23         9    119.0  80.0  35.0      0.0  29.0     0.263  29.0
24        11    143.0  94.0  33.0    146.0  36.6     0.254  51.0
25        10    125.0  70.0  26.0    115.0  31.1     0.205  41.0
26         7    147.0  76.0   0.0      0.0  39.4     0.257  43.0
27         1     97.0  66.0  15.0    140.0  23.2     0.487  22.0
28        13    145.0  82.0  19.0    110.0  22.2     0.245  57.0
29         5    117.0  92.0   0.0      0.0  34.1     0.337  38.0
..       ...      ...   ...   ...      ...   ...       ...   ...
737        8     65.0  72.0  23.0      0.0  32.0     0.600  42.0
738        2     99.0  60.0  17.0    160.0  36.6     0.453  21.0
739        1    102.0  74.0   0.0      0.0  39.5     0.293  42.0
740       11    120.0  80.0  37.0    150.0  42.3     0.785  48.0
741        3    102.0  44.0  20.0     94.0  30.8     0.400  26.0
742        1    109.0  58.0  18.0    116.0  28.5     0.219  22.0
743        9    140.0  94.0   0.0      0.0  32.7     0.734  45.0
744       13    153.0  88.0  37.0    140.0  40.6     1.174  39.0
745       12    100.0  84.0  33.0    105.0  30.0     0.488  46.0
746        1    147.0  94.0  41.0      0.0  49.3     0.358  27.0
747        1     81.0  74.0  41.0     57.0  46.3     1.096  32.0
748        3    187.0  70.0  22.0    200.0  36.4     0.408  36.0
749        6    162.0  62.0   0.0      0.0  24.3     0.178  50.0
750        4    136.0  70.0   0.0      0.0  31.2     1.182  22.0
751        1    121.0  78.0  39.0     74.0  39.0     0.261  28.0
752        3    108.0  62.0  24.0      0.0  26.0     0.223  25.0
753        0    181.0  88.0  44.0    510.0  43.3     0.222  26.0
754        8    154.0  78.0  32.0      0.0  32.4     0.443  45.0
755        1    128.0  88.0  39.0    110.0  36.5     1.057  37.0
756        7    137.0  90.0  41.0      0.0  32.0     0.391  39.0
757        0    123.0  72.0   0.0      0.0  36.3     0.258  52.0
758        1    106.0  76.0   0.0      0.0  37.5     0.197  26.0
759        6    190.0  92.0   0.0      0.0  35.5     0.278  66.0
760        2     88.0  58.0  26.0     16.0  28.4     0.766  22.0
761        9    170.0  74.0  31.0      0.0  44.0     0.403  43.0
762        9     89.0  62.0   0.0      0.0  22.5     0.142  33.0
763       10    101.0  76.0  48.0    180.0  32.9     0.171  63.0
764        2    122.0  70.0  27.0      0.0  36.8     0.340  27.0
765        5    121.0  72.0  23.0    112.0  26.2     0.245  30.0
766        1    126.0  60.0   0.0      

In [54]:
y = df.label
y

0      1.0
1      0.0
2      1.0
3      0.0
4      1.0
5      0.0
6      1.0
7      0.0
8      1.0
9      1.0
10     0.0
11     1.0
12     0.0
13     1.0
14     1.0
15     1.0
16     1.0
17     1.0
18     0.0
19     1.0
20     0.0
21     0.0
22     1.0
23     1.0
24     1.0
25     1.0
26     1.0
27     0.0
28     0.0
29     0.0
      ... 
737    0.0
738    0.0
739    1.0
740    1.0
741    0.0
742    0.0
743    1.0
744    0.0
745    0.0
746    1.0
747    0.0
748    1.0
749    1.0
750    1.0
751    0.0
752    0.0
753    1.0
754    1.0
755    1.0
756    0.0
757    1.0
758    0.0
759    1.0
760    0.0
761    1.0
762    0.0
763    0.0
764    0.0
765    0.0
766    1.0
Name: label, Length: 767, dtype: float64

In [55]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
x=scale.fit_transform(x)

In [56]:
x

array([[ 0.63872696,  0.8470548 ,  0.14960376, ...,  0.20362197,
         0.467638  ,  1.42463671],
       [-0.84582934, -1.124361  , -0.16038116, ..., -0.6842578 ,
        -0.36549383, -0.19177802],
       [ 1.23254948,  1.9422858 , -0.26370947, ..., -1.10282969,
         0.60347471, -0.10670356],
       ...,
       [-0.54891808,  0.03345463,  0.04627545, ...,  0.60950986,
        -0.39869836, -0.53207586],
       [ 0.3418157 ,  0.00216231,  0.14960376, ..., -0.73499379,
        -0.68546474, -0.27685248],
       [-0.84582934,  0.15862388, -0.47036608, ..., -0.24031791,
        -0.37153101,  1.16941333]])

In [57]:
x.shape

(767, 8)

In [62]:
y=y.values

In [63]:
y=y.reshape(-1,1)

In [65]:
y.shape

(767, 1)

In [66]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.22,random_state=45)

In [67]:
lr=LogisticRegression()

In [68]:
x_train.shape

(598, 8)

In [69]:
x_test.shape

(169, 8)

In [70]:
y_train.shape

(598, 1)

In [71]:
y_test.shape

(169, 1)

In [72]:
lr.fit(x_train,y_train)
lr.score(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7909698996655519

In [73]:
predlr=lr.predict(x_test)
print(accuracy_score(y_test,predlr))
print(confusion_matrix(y_test,predlr))
print(classification_report(y_test,predlr))


0.7337278106508875
[[94 19]
 [26 30]]
              precision    recall  f1-score   support

         0.0       0.78      0.83      0.81       113
         1.0       0.61      0.54      0.57        56

    accuracy                           0.73       169
   macro avg       0.70      0.68      0.69       169
weighted avg       0.73      0.73      0.73       169



In [74]:
gnb=GaussianNB()
gnb.fit(x_train,y_train)
gnb.score(x_train,y_train)
predgnb=gnb.predict(x_test)
print(accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))



0.7396449704142012
[[91 22]
 [22 34]]
              precision    recall  f1-score   support

         0.0       0.81      0.81      0.81       113
         1.0       0.61      0.61      0.61        56

    accuracy                           0.74       169
   macro avg       0.71      0.71      0.71       169
weighted avg       0.74      0.74      0.74       169



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [75]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt.score(x_train,y_train)
preddt=dt.predict(x_test)
print(accuracy_score(y_test,preddt))
print(confusion_matrix(y_test,preddt))
print(classification_report(y_test,preddt))



0.6627218934911243
[[82 31]
 [26 30]]
              precision    recall  f1-score   support

         0.0       0.76      0.73      0.74       113
         1.0       0.49      0.54      0.51        56

    accuracy                           0.66       169
   macro avg       0.63      0.63      0.63       169
weighted avg       0.67      0.66      0.67       169



In [76]:
svc=SVC()
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.7396449704142012
[[95 18]
 [26 30]]
              precision    recall  f1-score   support

         0.0       0.79      0.84      0.81       113
         1.0       0.62      0.54      0.58        56

    accuracy                           0.74       169
   macro avg       0.71      0.69      0.69       169
weighted avg       0.73      0.74      0.73       169



In [77]:
KN=KNeighborsClassifier()
KN.fit(x_train,y_train)
KN.score(x_train,y_train)
predKN=KN.predict(x_test)
print(accuracy_score(y_test,predKN))
print(confusion_matrix(y_test,predKN))
print(classification_report(y_test,predKN))



C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


0.7218934911242604
[[89 24]
 [23 33]]
              precision    recall  f1-score   support

         0.0       0.79      0.79      0.79       113
         1.0       0.58      0.59      0.58        56

    accuracy                           0.72       169
   macro avg       0.69      0.69      0.69       169
weighted avg       0.72      0.72      0.72       169

