In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, LabelEncoder


In [2]:
mushroom=pd.read_csv("Mushroom.csv")

In [3]:
mushroom

Class Cap-shape Cap-surface Cap-color Bruises Odor Gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
5        e         x           y         y       t    a               f   
6        e         b           s         w       t    a               f   
7        e         b           y         w       t    l               f   
8        p         x           y         w       t    p               f   
9        e         b           s         y       t    a               f   
10       e         x           y         y       t    l               f   
11       e         x           y         y       t    a               f   
12       e         b           s         y       t    a               f   
13       p         x           y         w       t    p               f   
14       e         x           f         n       f    n               f   
15       e         s           f         g       f    n               f   
16       e         f           f         w       f    n               f   
17       p         x           s         n       t    p               f   
18       p         x           y         w       t    p               f   
19       p         x           s         n       t    p               f   
20       e         b           s         y       t    a               f   
21       p         x           y         n       t    p               f   
22       e         b           y         y       t    l               f   
23       e         b           y         w       t    a               f   
24       e         b           s         w       t    l               f   
25       p         f           s         w       t    p               f   
26       e         x           y         y       t    a               f   
27       e         x           y         w       t    l               f   
28       e         f           f         n       f    n               f   
29       e         x           s         y       t    a               f   
...    ...       ...         ...       ...     ...  ...             ...   
8094     e         b           s         g       f    n               f   
8095     p         x           y         c       f    m               f   
8096     e         k           f         w       f    n               f   
8097     p         k           y         n       f    s               f   
8098     p         k           s         e       f    y               f   
8099     e         k           f         w       f    n               f   
8100     e         f           s         n       f    n               a   
8101     p         k           s         e       f    s               f   
8102     e         x           s         n       f    n               a   
8103     e         k           s         n       f    n               a   
8104     e         k           s         n       f    n               a   
8105     e         k           s         n       f    n               a   
8106     e         k           s         n       f    n               a   
8107     e         x           s         n       f    n               a   
8108     p         k           y         e       f    y               f   
8109     e         b           s         w       f    n               f   
8110     e         x           s         n       f    n               a   
8111     e         k           s         w       f    n               f   
8112     e         k           s         n       f    n               a   
8113     p         k           y         e       f    y               f   
8114     p         f           y         c       f    m               a   
8115     e         x          

In [4]:
df=pd.DataFrame(data=mushroom)

In [5]:
df.head()

Class Cap-shape Cap-surface Cap-color Bruises Odor Gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  Gill-spacing Gill-size Gill-color  ... Stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  Stalk-color-above-ring Stalk-color-below-ring Veil-type Veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  Ring-number Ring-type Spore-print-color Population Habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [6]:
df.isnull().sum()

Class                       0
Cap-shape                   0
Cap-surface                 0
Cap-color                   0
Bruises                     0
Odor                        0
Gill-attachment             0
Gill-spacing                0
Gill-size                   0
Gill-color                  0
Stalk-shape                 0
Stalk-root                  0
Stalk-surface-above-ring    0
Stalk-surface-below-ring    0
Stalk-color-above-ring      0
Stalk-color-below-ring      0
Veil-type                   0
Veil-color                  0
Ring-number                 0
Ring-type                   0
Spore-print-color           0
Population                  0
Habitat                     0
dtype: int64

In [7]:
df.columns

Index(['Class', 'Cap-shape', 'Cap-surface', 'Cap-color', 'Bruises', 'Odor',
       'Gill-attachment', 'Gill-spacing', 'Gill-size', 'Gill-color',
       'Stalk-shape', 'Stalk-root', 'Stalk-surface-above-ring',
       'Stalk-surface-below-ring', 'Stalk-color-above-ring',
       'Stalk-color-below-ring', 'Veil-type', 'Veil-color', 'Ring-number',
       'Ring-type', 'Spore-print-color', 'Population', 'Habitat'],
      dtype='object')

In [8]:
df.describe()

Class Cap-shape Cap-surface Cap-color Bruises  Odor Gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       Gill-spacing Gill-size Gill-color  ... Stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       Stalk-color-above-ring Stalk-color-below-ring Veil-type Veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       Ring-number Ring-type Spore-print-color Population Habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [9]:
df=pd.get_dummies(df)

In [10]:
df.describe()

Class_e      Class_p  Cap-shape_b  Cap-shape_c  Cap-shape_f  \
count  8124.000000  8124.000000  8124.000000  8124.000000  8124.000000   
mean      0.517971     0.482029     0.055638     0.000492     0.387986   
std       0.499708     0.499708     0.229235     0.022185     0.487321   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       1.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     1.000000     0.000000     0.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

       Cap-shape_k  Cap-shape_s  Cap-shape_x  Cap-surface_f  Cap-surface_g  \
count  8124.000000  8124.000000  8124.000000    8124.000000    8124.000000   
mean      0.101920     0.003939     0.450025       0.285574       0.000492   
std       0.302562     0.062641     0.497527       0.451715       0.022185   
min       0.000000     0.000000     0.000000       0.000000       0.000000   
25%       0.000000     0.000000     0.000000       0.000000       0.000000   
50%       0.000000     0.000000     0.000000       0.000000       0.000000   
75%       0.000000     0.000000     1.000000       1.000000       0.000000   
max       1.000000     1.000000     1.000000       1.000000       1.000000   

       ...  Population_s  Population_v  Population_y    Habitat_d  \
count  ...   8124.000000   8124.000000   8124.000000  8124.000000   
mean   ...      0.153619      0.497292      0.210734     0.387494   
std    ...      0.360605      0.500023      0.407855     0.487208   
min    ...      0.000000      0.000000      0.000000     0.000000   
25%    ...      0.000000      0.000000      0.000000     0.000000   
50%    ...      0.000000      0.000000      0.000000     0.000000   
75%    ...      0.000000      1.000000      0.000000     1.000000   
max    ...      1.000000      1.000000      1.000000     1.000000   

         Habitat_g    Habitat_l    Habitat_m    Habitat_p    Habitat_u  \
count  8124.000000  8124.000000  8124.000000  8124.000000  8124.000000   
mean      0.264402     0.102413     0.035943     0.140817     0.045298   
std       0.441041     0.303209     0.186159     0.347854     0.207969   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     0.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

         Habitat_w  
count  8124.000000  
mean      0.023634  
std       0.151914  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       1.000000  

[8 rows x 119 columns]

In [11]:
x=df.drop(['Class_e'],axis=1)

In [12]:
x=x.drop(["Class_p"],axis=1).values


In [13]:
x

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [14]:
y=df.iloc[:,0:2]

In [15]:
y.values

array([[0, 1],
       [1, 0],
       [1, 0],
       ...,
       [1, 0],
       [0, 1],
       [1, 0]], dtype=uint8)

In [16]:
y.shape

(8124, 2)

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=43)

In [19]:
model = RandomForestClassifier()
model.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [20]:
test_pred = model.predict(x_test)

In [21]:
accuracy_score(y_test, test_pred)

1.0

In [22]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
score=cross_val_score(model,x,y,cv=5,scoring="accuracy")


In [23]:
print(score)

[0.97538462 1.         1.         1.         0.99507389]
