In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings("ignore")

In [2]:
sonar=pd.read_csv("sonar.csv",names=range(0,61),header=0)

In [3]:
sonar

0       1       2       3       4       5       6       7       8   \
0    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
5    0.0317  0.0956  0.1321  0.1408  0.1674  0.1710  0.0731  0.1401  0.2083   
6    0.0519  0.0548  0.0842  0.0319  0.1158  0.0922  0.1027  0.0613  0.1465   
7    0.0223  0.0375  0.0484  0.0475  0.0647  0.0591  0.0753  0.0098  0.0684   
8    0.0164  0.0173  0.0347  0.0070  0.0187  0.0671  0.1056  0.0697  0.0962   
9    0.0039  0.0063  0.0152  0.0336  0.0310  0.0284  0.0396  0.0272  0.0323   
10   0.0123  0.0309  0.0169  0.0313  0.0358  0.0102  0.0182  0.0579  0.1122   
11   0.0079  0.0086  0.0055  0.0250  0.0344  0.0546  0.0528  0.0958  0.1009   
12   0.0090  0.0062  0.0253  0.0489  0.1197  0.1589  0.1392  0.0987  0.0955   
13   0.0124  0.0433  0.0604  0.0449  0.0597  0.0355  0.0531  0.0343  0.1052   
14   0.0298  0.0615  0.0650  0.0921  0.1615  0.2294  0.2176  0.2033  0.1459   
15   0.0352  0.0116  0.0191  0.0469  0.0737  0.1185  0.1683  0.1541  0.1466   
16   0.0192  0.0607  0.0378  0.0774  0.1388  0.0809  0.0568  0.0219  0.1037   
17   0.0270  0.0092  0.0145  0.0278  0.0412  0.0757  0.1026  0.1138  0.0794   
18   0.0126  0.0149  0.0641  0.1732  0.2565  0.2559  0.2947  0.4110  0.4983   
19   0.0473  0.0509  0.0819  0.1252  0.1783  0.3070  0.3008  0.2362  0.3830   
20   0.0664  0.0575  0.0842  0.0372  0.0458  0.0771  0.0771  0.1130  0.2353   
21   0.0099  0.0484  0.0299  0.0297  0.0652  0.1077  0.2363  0.2385  0.0075   
22   0.0115  0.0150  0.0136  0.0076  0.0211  0.1058  0.1023  0.0440  0.0931   
23   0.0293  0.0644  0.0390  0.0173  0.0476  0.0816  0.0993  0.0315  0.0736   
24   0.0201  0.0026  0.0138  0.0062  0.0133  0.0151  0.0541  0.0210  0.0505   
25   0.0151  0.0320  0.0599  0.1050  0.1163  0.1734  0.1679  0.1119  0.0889   
26   0.0177  0.0300  0.0288  0.0394  0.0630  0.0526  0.0688  0.0633  0.0624   
27   0.0100  0.0275  0.0190  0.0371  0.0416  0.0201  0.0314  0.0651  0.1896   
28   0.0189  0.0308  0.0197  0.0622  0.0080  0.0789  0.1440  0.1451  0.1789   
29   0.0240  0.0218  0.0324  0.0569  0.0330  0.0513  0.0897  0.0713  0.0569   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
177  0.0197  0.0394  0.0384  0.0076  0.0251  0.0629  0.0747  0.0578  0.1357   
178  0.0394  0.0420  0.0446  0.0551  0.0597  0.1416  0.0956  0.0802  0.1618   
179  0.0310  0.0221  0.0433  0.0191  0.0964  0.1827  0.1106  0.1702  0.2804   
180  0.0423  0.0321  0.0709  0.0108  0.1070  0.0973  0.0961  0.1323  0.2462   
181  0.0095  0.0308  0.0539  0.0411  0.0613  0.1039  0.1016  0.1394  0.2592   
182  0.0096  0.0404  0.0682  0.0688  0.0887  0.0932  0.0955  0.2140  0.2546   
183  0.0269  0.0383  0.0505  0.0707  0.1313  0.2103  0.2263  0.2524  0.3595   
184  0.0340  0.0625  0.0381  0.0257  0.0441  0.1027  0.1287  0.1850  0.2647   
185  0.0209  0.0191  0.0411  0.0321  0.0698  0.1579  0.1438  0.1402  0.3048   
186  0.0368  0.0279  0.0103  0.0566  0.0759  0.0679  0.0970  0.1473  0.2164   
187  0.0089  0.0274  0.0248  0.0237  0.0224  0.0845  0.1488  0.1224  0.1569   
188  0.0158  0.0239  0.0150  0.0494  0.0988  0.1425  0.1463  0.1219  0.1697   
189  0.0156  0.0210  0.0282  0.0596  0.0462  0.0779  0.1365  0.0780  0.1038   
190  0.0315  0.0252  0.0167  0.0479  0.0902  0.1057  0.1024  0.1209  0.1241   
191  0.0056  0.0267  0.0221  0.0561  0.0936  0.1146  0.0706  0.0996  0.1673   
192  0.0203  0.0121  0.0380  0.0128  0.0537  0.0874  0.1021  0.0852  0.1136   
193  0.0392  0.0108  0.0267  0.0257  0.0410  0.0491  0.1053  0.1690  0.2105   
194  0.0129  0.0141  0.0309  0.0375  0.0767  0.0787  0.0662  0.1108  0.1777   
195  0.0050  0.0017  0.0270  0.0450  0.0958  0.0830  0.0879

In [4]:
df=pd.DataFrame(data=sonar)

In [5]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

       9   ...      51      52      53      54      55      56      57  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

       58      59  60  
0  0.0052  0.0044   R  
1  0.0095  0.0078   R  
2  0.0040  0.0117   R  
3  0.0107  0.0094   R  
4  0.0051  0.0062   R  

[5 rows x 61 columns]

In [6]:
df.describe()

0           1           2           3           4           5   \
count  207.000000  207.000000  207.000000  207.000000  207.000000  207.000000   
mean     0.029208    0.038443    0.043837    0.054053    0.075105    0.104599   
std      0.023038    0.033040    0.038521    0.046583    0.055669    0.059247   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013300    0.016400    0.018900    0.024450    0.037700    0.066950   
50%      0.022800    0.030800    0.034200    0.044100    0.062000    0.092100   
75%      0.035800    0.048100    0.058200    0.065700    0.101050    0.134150   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

               6           7           8           9   ...          50  \
count  207.000000  207.000000  207.000000  207.000000  ...  207.000000   
mean     0.121591    0.134677    0.177361    0.208245  ...    0.016034   
std      0.061897    0.085340    0.118311    0.134741  ...    0.012027   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080600    0.080350    0.096750    0.111150  ...    0.008350   
50%      0.105600    0.111900    0.152200    0.181000  ...    0.013800   
75%      0.153050    0.169800    0.231500    0.269000  ...    0.020700   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

               51          52          53          54          55          56  \
count  207.000000  207.000000  207.000000  207.000000  207.000000  207.000000   
mean     0.013472    0.010729    0.010917    0.009300    0.008181    0.007771   
std      0.009628    0.007071    0.007310    0.007103    0.005719    0.005756   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007350    0.005050    0.005350    0.004100    0.004400    0.003700   
50%      0.011500    0.009600    0.009300    0.007500    0.006800    0.005900   
75%      0.016750    0.014900    0.014450    0.012100    0.010350    0.010350   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

               57          58          59  
count  207.000000  207.000000  207.000000  
mean     0.007947    0.007936    0.006523  
std      0.006485    0.006196    0.005038  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003650    0.003100  
50%      0.005800    0.006300    0.005300  
75%      0.010400    0.010350    0.008550  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

In [7]:
x=df.iloc[:,0:-1]

In [8]:
pca = PCA(n_components=10)

In [9]:
xpca=pca.fit_transform(x)
x=xpca

In [10]:
pd.DataFrame(data=x)

0         1         2         3         4         5         6  \
0   -0.970285  1.017654  0.830432  0.120147  0.299120  0.202682 -0.226988   
1   -0.324435  0.876876  0.228203  0.868926  0.098053 -0.269122 -0.421778   
2    0.853571  0.697734 -0.023602 -0.123425 -0.584388  0.351808  0.478187   
3   -0.061337  0.226034  0.635198  0.152907  0.150982  0.081111 -0.374523   
4   -0.605423  0.901962  0.804550  0.271896  0.496832  0.464410 -0.224909   
5   -0.155512  0.397189 -0.236508 -0.184495 -0.219554  0.377336  0.022937   
6   -0.605470 -0.050505  0.001244 -0.237550 -0.664685  0.061253 -0.135593   
7   -0.381704 -0.075134 -0.029934 -0.257844 -0.536723 -0.506412  0.099131   
8   -0.176107 -1.010684  0.088104 -0.314870  0.007677 -0.104833  0.208576   
9    1.121184 -0.458966  0.177197 -0.288348  0.310049 -0.208691 -0.029574   
10  -0.106705 -0.263267  0.039528 -0.319364 -0.391495 -0.422232 -0.284659   
11  -0.940904  0.224908 -0.152609 -0.704344 -0.224894 -0.193290  0.345440   
12   0.425360  0.056089  0.015738 -0.129001  0.030468  0.348219 -0.198542   
13   0.051528  0.192575  0.009238 -0.401783 -0.485005  0.110280 -0.178216   
14   0.491857  0.483175 -0.202715 -0.209316  0.481878  0.066035 -0.104808   
15   0.957630  0.409409 -0.123540  0.057410  0.046969  0.037284  0.053658   
16  -0.271263  0.920524 -0.328589 -0.421034 -0.090029  0.598527  0.155193   
17   0.490338 -0.208931 -0.250739  0.013894  0.671392  0.079170 -0.354134   
18  -1.348339  0.640596  0.239897  0.174964 -0.383288 -0.048684 -0.057778   
19   0.231539  0.847275 -0.601103  0.042717  0.085349 -0.462631  0.291277   
20   1.064569  1.371856 -0.010159  0.241052  0.259810  0.016913 -0.077623   
21   1.591744  1.206355  0.186906  0.140388 -0.352558  0.462588  0.262794   
22   0.839770 -0.091457  0.180911 -0.027746  0.536786 -0.454186 -0.102716   
23   1.272468  0.633873  0.041001 -0.620160  0.484712 -0.222344  0.483404   
24   1.122370 -0.534688 -0.402314  0.007445  0.500027 -0.281233  0.440886   
25  -0.913345  0.132064  0.078133 -0.365047  0.036030  0.036367  0.167238   
26  -0.333431 -0.435699  0.314493  0.016409  0.404244  0.286652  0.114079   
27  -0.674347  0.559539 -0.251874 -0.398369 -0.146109 -0.151630  0.030528   
28  -0.335773 -0.093118  0.713440 -0.184253 -0.079845 -0.056423 -0.233137   
29  -0.084998 -0.423465  0.051034  0.012157  0.156758  0.043469 -0.221829   
..        ...       ...       ...       ...       ...       ...       ...   
177  0.306020 -0.646297  0.241600 -0.022086  0.009268 -0.129839  0.061039   
178  0.291160 -0.454656  0.084138  0.277234  0.160674 -0.214163  0.233465   
179 -0.155897 -0.350416 -0.061307  0.615945 -0.560529 -0.235360  0.024765   
180  0.370414 -0.231302  0.010363  0.870798 -0.459328  0.220704  0.207816   
181  0.152069 -0.174330 -0.012127  0.783319 -0.367743 -0.037895 -0.070156   
182  0.052993 -0.286210 -0.165607  0.854433 -0.423896 -0.027690 -0.065236   
183 -0.289793 -0.219833 -0.103814  0.637888 -0.702174 -0.169219 -0.236387   
184 -0.127243 -0.315968 -0.134459  0.824269 -0.530716 -0.193142 -0.056837   
185  0.612040 -0.140907  0.414713  0.923423 -0.274005  0.186291  0.500590   
186  0.538390 -0.406372  0.640594  0.259354 -0.035018 -0.070475  0.102055   
187  0.482475 -0.574662  0.564374  0.129783 -0.089619 -0.072145  0.083185   
188  0.258542 -0.607596  0.504631  0.099862 -0.004531 -0.117051 -0.043023   
189  0.366702 -0.659581  0.491892  0.065553 -0.011654 -0.023369 -0.001823   
190  0.273982 -0.737167  0.459841  0.004325 -0.091029  0.048325 -0.025466   
191  0.235252 -0.745730  0.538385 -0.007782 -0.092164 -0.001920 -0.036003   
192  0.423267 -0.730424  0.450763  0.003781 -0.066970 -0.007834 -0.001557   
193  0.092906 -0.962154  0.255198  0.111072 -0.043990 -0.174753 -0.064150   
194 -0.308393 -0.929487  0.096720  0.215664 -0.216991 -0.171219  0.019095   
195 -0.498100 -0.943673 -0.036998  0.140693 -0.222871 -0.267697 -0.062500   
196 -0.360313 -0.913039 -0.030093  0.046618 -0.232083 -0.208407 -0.006618   
197 -0.3

In [11]:
y=df.iloc[:,-1]

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
scale=StandardScaler()

In [15]:
x.shape

(207, 10)

In [16]:
x.shape

(207, 10)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.22,random_state=45)

In [18]:
x=scale.fit_transform(x)

In [19]:
x

array([[-1.29978169,  1.70606442,  2.15236817, ...,  1.79447233,
         0.02192769, -0.45429916],
       [-0.43460945,  1.47005543,  0.59147287, ...,  0.37803268,
         0.07184752, -2.37555778],
       [ 1.14343337,  1.16972949, -0.06117199, ..., -1.00450695,
        -2.70454535, -2.33625944],
       ...,
       [ 0.41093512, -1.92417588,  0.64531104, ...,  1.06252591,
        -0.3552279 , -1.72146488],
       [-0.05101567, -1.66649159,  0.5233967 , ...,  0.32409149,
        -0.12362156, -0.90829238],
       [-0.05881343, -1.52693138,  0.02376526, ..., -0.08906321,
         0.60847198, -0.75807236]])

In [20]:
lr=LogisticRegression()

In [21]:
x_train.shape

(161, 10)

In [22]:
x_test.shape

(46, 10)

In [23]:
y_train=y_train.reshape(-1,1)

In [24]:
y_train.shape

(161, 1)

In [25]:
y_test=y_test.reshape(-1,1)

In [26]:
y_test.shape

(46, 1)

In [27]:
lr.fit(x_train,y_train)
lr.score(x_train,y_train)

0.7329192546583851

In [28]:
predlr=lr.predict(x_test)
print(accuracy_score(y_test,predlr))
print(confusion_matrix(y_test,predlr))
print(classification_report(y_test,predlr))


0.782608695652174
[[23  1]
 [ 9 13]]
              precision    recall  f1-score   support

           0       0.72      0.96      0.82        24
           1       0.93      0.59      0.72        22

    accuracy                           0.78        46
   macro avg       0.82      0.77      0.77        46
weighted avg       0.82      0.78      0.77        46



In [29]:
gnb=GaussianNB()
gnb.fit(x_train,y_train)
gnb.score(x_train,y_train)
predgnb=gnb.predict(x_test)
print(accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))



0.782608695652174
[[21  3]
 [ 7 15]]
              precision    recall  f1-score   support

           0       0.75      0.88      0.81        24
           1       0.83      0.68      0.75        22

    accuracy                           0.78        46
   macro avg       0.79      0.78      0.78        46
weighted avg       0.79      0.78      0.78        46



In [30]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt.score(x_train,y_train)
preddt=dt.predict(x_test)
print(accuracy_score(y_test,preddt))
print(confusion_matrix(y_test,preddt))
print(classification_report(y_test,preddt))



0.6956521739130435
[[17  7]
 [ 7 15]]
              precision    recall  f1-score   support

           0       0.71      0.71      0.71        24
           1       0.68      0.68      0.68        22

    accuracy                           0.70        46
   macro avg       0.70      0.70      0.70        46
weighted avg       0.70      0.70      0.70        46



In [31]:
svc=SVC()
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))



0.6956521739130435
[[22  2]
 [12 10]]
              precision    recall  f1-score   support

           0       0.65      0.92      0.76        24
           1       0.83      0.45      0.59        22

    accuracy                           0.70        46
   macro avg       0.74      0.69      0.67        46
weighted avg       0.74      0.70      0.68        46



In [32]:
def lr():
    KN=KNeighborsClassifier()
    KN.fit(x_train,y_train)
    KN.score(x_train,y_train)
    predKN=KN.predict(x_test)
    print(accuracy_score(y_test,predKN))
    print(confusion_matrix(y_test,predKN))
    print(classification_report(y_test,predKN))



In [33]:
lr()

0.8043478260869565
[[22  2]
 [ 7 15]]
              precision    recall  f1-score   support

           0       0.76      0.92      0.83        24
           1       0.88      0.68      0.77        22

    accuracy                           0.80        46
   macro avg       0.82      0.80      0.80        46
weighted avg       0.82      0.80      0.80        46



In [34]:
from sklearn.externals import joblib
joblib.dump(lr,"lrsave")

['lrsave']

In [35]:
import pickle
s=pickle.dumps(lr)
clf2=pickle.loads(s)

In [36]:
clf2

<function __main__.lr()>