In [13]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [14]:
data=pd.read_csv("breast_cancer.csv")

In [15]:
data.columns = ['Sample Code Number','Clump Thickness','Uniformity of Cell Size',
                                                        'Uniformity of Cell Shape','Marginal Adhesion','Single Epithelial Cell Size',
                                                        'Bare Nuclei','Bland Chromatin','Normal Nucleoli','Mitoses','Class']

In [16]:
data.head(10)

Sample Code Number  Clump Thickness  Uniformity of Cell Size  \
0             1002945                5                        4   
1             1015425                3                        1   
2             1016277                6                        8   
3             1017023                4                        1   
4             1017122                8                       10   
5             1018099                1                        1   
6             1018561                2                        1   
7             1033078                2                        1   
8             1033078                4                        2   
9             1035283                1                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         4                  5                            7   
1                         1                  1                            2   
2                         8                  1                            3   
3                         1                  3                            2   
4                        10                  8                            7   
5                         1                  1                            2   
6                         2                  1                            2   
7                         1                  1                            2   
8                         1                  1                            2   
9                         1                  1                            1   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0          10                3                2        1      2  
1           2                3                1        1      2  
2           4                3                7        1      2  
3           1                3                1        1      2  
4          10                9                7        1      4  
5          10                3                1        1      2  
6           1                3                1        1      2  
7           1                1                1        5      2  
8           1                2                1        1      2  
9           1                3                1        1      2

In [17]:
data.isnull().sum()

Sample Code Number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [18]:
data = data.drop(['Sample Code Number'],axis=1)
data = data[data['Bare Nuclei'] != '?']
data['Class'] = np.where(data['Class'] ==2,0,1)
data['Class'].value_counts()

0    443
1    239
Name: Class, dtype: int64

In [19]:
X = data.drop(['Class'],axis=1)
y = data['Class']

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [21]:
from sklearn.dummy import DummyClassifier
clf = DummyClassifier(strategy= 'most_frequent').fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [22]:
print('y actual : \n' +  str(y_test.value_counts()))

y actual : 
0    112
1     59
Name: Class, dtype: int64


In [23]:
print('y predicted : \n' + str(pd.Series(y_pred).value_counts()))

y predicted : 
0    171
dtype: int64


In [24]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score
print('Accuracy Score : ' + str(accuracy_score(y_test,y_pred)))
print('Precision Score : ' + str(precision_score(y_test,y_pred)))
print('Recall Score : ' + str(recall_score(y_test,y_pred)))
print('F1 Score : ' + str(f1_score(y_test,y_pred)))


Accuracy Score : 0.6549707602339181
Precision Score : 0.0
Recall Score : 0.0
F1 Score : 0.0


In [25]:
from sklearn.metrics import confusion_matrix
print('Confusion Matrix : \n' + str(confusion_matrix(y_test,y_pred)))

Confusion Matrix : 
[[112   0]
 [ 59   0]]


In [26]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression().fit(X_train,y_train)
y_pred = clf.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score
print('Accuracy Score : ' + str(accuracy_score(y_test,y_pred)))
print('Precision Score : ' + str(precision_score(y_test,y_pred)))
print('Recall Score : ' + str(recall_score(y_test,y_pred)))
print('F1 Score : ' + str(f1_score(y_test,y_pred)))

Accuracy Score : 0.9532163742690059
Precision Score : 0.9636363636363636
Recall Score : 0.8983050847457628
F1 Score : 0.9298245614035089


In [28]:
from sklearn.metrics import confusion_matrix
print('Confusion Matrix : \n' + str(confusion_matrix(y_test,y_pred)))

Confusion Matrix : 
[[110   2]
 [  6  53]]


In [29]:
from sklearn.model_selection import GridSearchCV
clf = LogisticRegression()
grid_values = {'penalty': ['l1', 'l2'],'C':[0.001,.009,0.01,.09,1,5,10,25]}
grid_clf_acc = GridSearchCV(clf, param_grid = grid_values,scoring = 'recall')
grid_clf_acc.fit(X_train, y_train)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.001, 0.009, 0.01, 0.09, 1, 5, 10, 25],
                         'penalty': ['l1', 'l2']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='recall', verbose=0)

In [30]:
y_pred_acc = grid_clf_acc.predict(X_test)

In [31]:
print('Accuracy Score : ' + str(accuracy_score(y_test,y_pred_acc)))
print('Precision Score : ' + str(precision_score(y_test,y_pred_acc)))
print('Recall Score : ' + str(recall_score(y_test,y_pred_acc)))
print('F1 Score : ' + str(f1_score(y_test,y_pred_acc)))

Accuracy Score : 0.9064327485380117
Precision Score : 0.7945205479452054
Recall Score : 0.9830508474576272
F1 Score : 0.8787878787878787


In [32]:
confusion_matrix(y_test,y_pred_acc)

array([[97, 15],
       [ 1, 58]], dtype=int64)